package com.example.activitytracker;


import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Spinner;

import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;

/*
Much of the content in this file was auto generated by Android studio, by clicking
new->activity->gallery... and then choosing "Google Maps Activity".
 */

public class MapsActivity extends FragmentActivity implements OnMapReadyCallback, AdapterView.OnItemSelectedListener {

    private GoogleMap mMap;
    private DistanceCalculator calculator = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_maps2);
        // Obtain the SupportMapFragment and get notified when the map is ready to be used.
        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);
        calculator = new DistanceCalculator(this);

        //Create a list that contains the last seven weekdays.
        ArrayList<String> dayList = new ArrayList<>();
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DATE, 1);
        for (int i = 0; i < 7; i++) {
            calendar.add(Calendar.DATE, -1);
            dayList.add(calendar.getDisplayName(Calendar.DAY_OF_WEEK, Calendar.LONG, Locale.ENGLISH));
        }

        //Populate the spinner with the last seven days.
        Spinner spinner = (Spinner) findViewById(R.id.day_spinner);
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this,
                R.layout.support_simple_spinner_dropdown_item, dayList);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
        spinner.setSelection(0);
    }

    public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
        //Handle that an item in the spinner has been clicked.
        Log.d("G53MDP", "Clicked item no. " + pos);
        placeMarkersForDay(pos);
    }

    public void onNothingSelected(AdapterView<?> parent) {

    }


    /**
     * Manipulates the map once available.
     * This callback is triggered when the map is ready to be used.
     * This is where we can add markers or lines, add listeners or move the camera. In this case,
     * we just add a marker near Sydney, Australia.
     * If Google Play services is not installed on the device, the user will be prompted to install
     * it inside the SupportMapFragment. This method will only be triggered once the user has
     * installed Google Play services and returned to the app.
     */
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
        placeMarkersForDay(0);

        //Set what happens when an item in the spinner is clicked.
        Spinner spinner = (Spinner) findViewById(R.id.day_spinner);
        spinner.setOnItemSelectedListener(this);
        /*
        // Add a marker in Sydney and move the camera
        LatLng sydney = new LatLng(-34, 151);
        mMap.addMarker(new MarkerOptions().position(sydney).title("Marker in Sydney"));
        mMap.moveCamera(CameraUpdateFactory.newLatLng(sydney));
        */
    }

    private void placeMarkersForDay(int daysAgo) {
        //Remove all previous markers.
        mMap.clear();
        //Retrieve all today's coordinates and timestamps.
        ArrayList<LatLng> coordinatesToday = calculator.getCoordinatesPerDay(daysAgo);
        ArrayList<String> timeatampsToday = calculator.getTimestampsPerDay(daysAgo);
        if (coordinatesToday.size() > 0) {
            //Mark out every tenth point on the map. Only every tenth is marked to avoid cluttering.
            //Every marker gets its timstamp as its title.
            for (int i = 0; i < coordinatesToday.size(); i += 10) {
                mMap.addMarker(new MarkerOptions().position(coordinatesToday.get(i)).title(timeatampsToday.get(i)));
            }
            //Move the camera to the last element.
            mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(coordinatesToday.get(coordinatesToday.size() - 1), 14));
            //Show the zoom button to allow zooming on the emulator which does not have multi-touch.
            mMap.getUiSettings().setZoomControlsEnabled(true);
        }
    }
}
